---
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - 443:443
    volumes:
      - ./ssl:/ssl
